### ISSUE TITLE
Remove solr/server directory from this repo

### ISSUE THREAD

**Issue by cmungall** [berkeleybop/bbop-manager-golr#7]
We have solr/server/solr/amigo/conf/managed-schema in this repo

And also a schema here:
https://github.com/geneontology/amigo/tree/master/golr/solr/conf

I don't know why Jeremy checked in the solr folder in the bbop-manager-golr repo, it seems totally out of place. I suggest deleting the whole solr folder here.

The proper place for the amigo schema is in the amigo repo

**Comment by cmungall** [comment]
After discussion with @kltm we will leave for future testing purposes, #8 adds a README that explains this

**Comment by cmungall** [comment]
It turns out there are functional tests Jeremy wrote:

https://github.com/berkeleybop/bbop-manager-golr/blob/master/gulpfile.js

These appear to do the full cycle of setting up a solr instance, loading it (both monarch and go loads) and testing

However, this is all likely stale. For testing purposes we should just use a standard image

**Comment by kltm** [comment]
Playing with it, [the mechanism] seems to work quite well and attempts to do as advertised on the box--test `bbop-golr-manager` with something other than theory.

That said, it does indeed no longer work, failing on the ontology load it has apparently. Which is odd considering the data is local...

```
2018-02-15 16:14:47,351 ERROR (GafCommandRunner:964) Unsatisfiable: GO:0035052 'dorsal vessel aortic cell fate commitment'
2018-02-15 16:14:47,351 INFO  (GafCommandRunner:966) Creating module for unsatisfiable classes in file: null
Exception in thread "main" java.lang.NullPointerException
	at java.io.File.<init>(File.java:277)
	at owltools.cli.GafCommandRunner.preCheckOntology(GafCommandRunner.java:974)
	at owltools.cli.SolrCommandRunner.flexLoadOntologySolr(SolrCommandRunner.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4054)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
```

from internal command:
```
java -Xms1024M -DentityExpansionLimit=4086000 -Djava.awt.headless=true -Xmx4G -jar ./java/lib/owltools-runner-all.jar _data/ontologies/go-gaf.owl _data/ontologies/eco.owl _data/ontologies/go-taxon-subsets.owl _data/ontologies/neurogenesis.obo --merge-support-ontologies --remove-subset-entities upperlevel --silence-elk --reasoner elk --solr-taxon-subset-name amigo_grouping_subset --solr-eco-subset-name go_groupings --solr-url http://localhost:8983/solr/amigo --solr-config _data/metadata/ont-config.yaml --solr-log /tmp/golr-load.log --solr-load-ontology --solr-load-ontology-general
```
